- name: Docker Image Build
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t ddung1203/java-hello-world java-hello-world/
    - command: docker login -u ddung1203 -p "{{ lookup('env', 'PASS') }}"
    - command: docker push ddung1203/java-hello-world
    - command: docker logout

- name: Docker Run
  hosts: docker_host
  gather_facts: false
    - command: docker container rm -f java-hello-world
      ignore_errors: yes
    - command: docker container run -d -p 8080:8080 --name java-hello-world java-hello-world
